### PR TITLE
Update create-batch

### PR DESCRIPTION
**Pull request by jshlee**
to allow generator and rivet jobs
not the best way

### CODE REVIEW

**Comment by jhgoh** [comment]
you are rilling back most recent updates for examplelines with basename function. Is there any special reason for that?

**Comment by jhgoh** [comment]
And just for a question - isnt there a randomseed problem with this?

**Comment by jshlee** [comment]
didnt know there was an updated version
what are the new features?

**Comment by jhgoh** [comment]
* Read cfg files from different directory - previously the cfg had to sit in the current dir.
  * Accept secondary files - useful for two file solutions
  * Customization cfg - override cfg with customise() function similarly to the cmsDriver.py command

**Comment by jshlee** [comment]
what about generation and other outputs like yoda?

**Comment by jhgoh** [comment]
--transferFiles output.yoda,another.root,yetAnother.txt

**Comment by jhgoh** [comment]
But does not support emptySource until now.

**Comment by jshlee** [comment]
one more thing. it needs to be able to keep some root files, i.e. the top kin fitting root file

**Comment by jhgoh** [comment]
Yes. the tar option should be changed. Are you going to fix this PR or do you want me to do it?

**Comment by jshlee** [comment]
i'll close this and since you know this better, could you

**Comment by jhgoh** [comment]
Done the last point. Let me thing how to implement other things with emptysource.

**Pull request closed without merging**
